Started logging messages at Sun Jul 15 00:54:50 2018
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 28 B-reps in file
Info:    Found 14 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 466
Info:            Created 
Info:        Working on 533
Info:            Created 
Info:        Working on 156
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1.52203e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 1
Info:        Working on 471
Info:            Created 
Info:        Working on 535
Info:            Created 
Info:        Working on 159
Info:            Created 
Info:        Created 
Info:    Working on BRep 1
Info:        Using 3D tolerance 3.52366e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 2
Info:        Working on 476
Info:            Created 
Info:        Working on 537
Info:            Created 
Info:        Working on 162
Info:            Created 
Info:        Created 
Info:    Working on BRep 2
Info:        Using 3D tolerance 1.99611e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 3
Info:        Working on 481
Info:            Created 
Info:        Working on 539
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Created 
Info:    Working on BRep 3
Info:        Using 3D tolerance 2.18459e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 4
Info:        Working on 486
Info:            Created 
Info:        Working on 541
Info:            Created 
Info:        Working on 168
Info:            Created 
Info:        Created 
Info:    Working on BRep 4
Info:        Using 3D tolerance 4.31936e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 5
Info:        Working on 491
Info:            Created 
Info:        Working on 543
Info:            Created 
Info:        Working on 171
Info:            Created 
Info:        Created 
Info:    Working on BRep 5
Info:        Using 3D tolerance 3.25913e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 6
Info:        Working on 496
Info:            Created 
Info:        Working on 545
Info:            Created 
Info:        Working on 174
Info:            Created 
Info:        Created 
Info:    Working on BRep 6
Info:        Using 3D tolerance 8.62005e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 7
Info:        Working on 501
Info:            Created 
Info:        Working on 547
Info:            Created 
Info:        Working on 177
Info:            Created 
Info:        Created 
Info:    Working on BRep 7
Info:        Using 3D tolerance 4.03597e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 8
Info:        Working on 506
Info:            Created 
Info:        Working on 549
Info:            Created 
Info:        Working on 180
Info:            Created 
Info:        Created 
Info:    Working on BRep 8
Info:        Using 3D tolerance 7.23061e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 9
Info:        Working on 511
Info:            Created 
Info:        Working on 551
Info:            Created 
Info:        Working on 183
Info:            Created 
Info:        Created 
Info:    Working on BRep 9
Info:        Using 3D tolerance 4.08005e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 10
Info:        Working on 516
Info:            Created 
Info:        Working on 553
Info:            Created 
Info:        Working on 186
Info:            Created 
Info:        Created 
Info:    Working on BRep 10
Info:        Using 3D tolerance 3.76792e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 11
Info:        Working on 521
Info:            Created 
Info:        Working on 555
Info:            Created 
Info:        Working on 189
Info:            Created 
Info:        Created 
Info:    Working on BRep 11
Info:        Using 3D tolerance 3.60182e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 12
Info:        Working on 526
Info:            Created 
Info:        Working on 557
Info:            Created 
Info:        Working on 192
Info:            Created 
Info:        Created 
Info:    Working on BRep 12
Info:        Using 3D tolerance 4.29374e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 13
Info:        Working on 531
Info:            Created 
Info:        Working on 559
Info:            Created 
Info:        Working on 195
Info:            Created 
Info:        Created 
Info:    Working on BRep 13
Info:        Using 3D tolerance 3.7543e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 14
Info:        Working on 434
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Created 
Info:    Working on curve 14
Info:        Created curve 
Info:    Working on 15
Info:        Working on 436
Info:            Created 
Info:        Working on 437
Info:            Created 
Info:        Created 
Info:    Working on curve 15
Info:        Created curve 
Info:    Working on 16
Info:        Working on 438
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Created 
Info:    Working on curve 16
Info:        Created curve 
Info:    Working on 17
Info:        Working on 440
Info:            Created 
Info:        Working on 441
Info:            Created 
Info:        Created 
Info:    Working on curve 17
Info:        Created curve 
Info:    Working on 18
Info:        Working on 442
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Created 
Info:    Working on curve 18
Info:        Created curve 
Info:    Working on 19
Info:        Working on 444
Info:            Created 
Info:        Working on 445
Info:            Created 
Info:        Created 
Info:    Working on curve 19
Info:        Created curve 
Info:    Working on 20
Info:        Working on 446
Info:            Created 
Info:        Working on 447
Info:            Created 
Info:        Created 
Info:    Working on curve 20
Info:        Created curve 
Info:    Working on 21
Info:        Working on 448
Info:            Created 
Info:        Working on 449
Info:            Created 
Info:        Created 
Info:    Working on curve 21
Info:        Created curve 
Info:    Working on 22
Info:        Working on 450
Info:            Created 
Info:        Working on 451
Info:            Created 
Info:        Created 
Info:    Working on curve 22
Info:        Created curve 
Info:    Working on 23
Info:        Working on 452
Info:            Created 
Info:        Working on 453
Info:            Created 
Info:        Created 
Info:    Working on curve 23
Info:        Created curve 
Info:    Working on 24
Info:        Working on 454
Info:            Created 
Info:        Working on 455
Info:            Created 
Info:        Created 
Info:    Working on curve 24
Info:        Created curve 
Info:    Working on 25
Info:        Working on 456
Info:            Created 
Info:        Working on 457
Info:            Created 
Info:        Created 
Info:    Working on curve 25
Info:        Created curve 
Info:    Working on 26
Info:        Working on 458
Info:            Created 
Info:        Working on 459
Info:            Created 
Info:        Created 
Info:    Working on curve 26
Info:        Created curve 
Info:    Working on 27
Info:        Working on 460
Info:            Created 
Info:        Working on 461
Info:            Created 
Info:        Created 
Info:    Working on curve 27
Info:        Created curve 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                14 found      14 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                 14 found      14 created       0 failed
Finished logging messages at Sun Jul 15 00:54:50 2018
